### ISSUE TITLE
Not send data with headers

### ISSUE THREAD

**Issue by zk231191** [ixudra/curl#100]
i cant send data with headers

**Comment by elimentz** [comment]
Please review the readme:

> Note before posting an issue: When posting an issue for the package, always be sure to provide as much information regarding the request as possible. This includes the example cURL request you are trying to transfer into the package syntax, your actual package syntax (the full request) and (if possible) an example URL I can use to test the request myself if need be.

**Comment by elimentz** [comment]
Closed due to inactivity
