### ISSUE TITLE
Method withOption wrong @param  $value type

### ISSUE THREAD

**Issue by jonathangoncalves** [ixudra/curl#101]
Hello!

The method withOption requires @param $value as string, but if I use HTTPHEADER option, require as Array ou Object, so the PHPDoc BLocks should be like this:

/**
     * Set any specific cURL option
     *
     * @param   string $key         The name of the cURL option
     * @param   string|array $value       The value to which the option is to be set
     * @return Builder
     */

**Comment by elimentz** [comment]
Fixed. Thanks for letting me know.
