### ISSUE TITLE
500 internal server error post json

### ISSUE THREAD

**Issue by WesleyVerbrugge** [ixudra/curl#103]
Hey ive been trying to get a API call for authentication on the AutoDNS api from my laravel 5.7 project with a POST request ran from a job but i cant seem to get it working 
Here is my code:

```
<?php
namespace App;
use Illuminate\Http\Request;
use Ixudra\Curl\Facades\Curl;

class autodns
{
  function curlConnect($domain) {
    // $response1 = Curl::to('http://localhost/apitest/apitest.php');
        $dataarray = array('user' => 'dashboard', 'context' => '33004', 'password' => 'LDq247A3Te3JgLhm');
        $response1 = Curl::to('https://api.autodns.com/v1/login')
        ->withData( ($dataarray) )
        ->enableDebug('C:\wamp64\www\API_QW\app\curllog\test.txt')
        ->returnResponseObject()
        ->asJson()
        ->withHeaders( array( 'Accept: application/json') )
        ->post();
    var_dump($response1);
    exit;
    $response2 = Curl::to('https://api.autodns.com/v1/domain/' . $domain)
        ->withData( array( 'name' => $domain ) )
        ->get();
    $result = json_decode($response2);
    var_dump($result);
    exit;
    $status_type = $result;
    return $response;
    }
}

```

The post function at the top is the one i cant get working for some reason

```
public function handle()
    {
        $client_id = $this->client_id;
        $module_identifier = $this->module_identifier;
        $client_id = $this->client_id;
        $module_identifier = $this->module_identifier;
        $cpanel = new cpanel;
        $rawResults = $cpanel->cpanel_get_domains($module_identifier);
        foreach($rawResults as $rawResult) {
          $domain = $rawResult['domain'];
          $checker = new autodns;
          $domainstatusjson = $checker->curlConnect($domain);
          $domainstatus = json_decode($domainstatusjson);
          var_dump($domainstatus);
          exit;
        }
    }

```

Once i dispatch the job from my controller with my API call i get a 500 internal server error as a response.
Ive confirmed that the credentials im using are correct and the same request crafted in postman seems to be working.
Anybody know whats wrong ?

**Comment by elimentz** [comment]
Syntax wise I can't see any mistakes. However, a 500 indicates a server problem of some sorts. Are you running a VM? And if you are, does your VM know that it should redirect the api call back to itself? I.e. have you updated your VM hosts file? Postman would not have this issue since it runs from the host system and not the VM

If not, I'd add some logging in the API handler and/or check the error and access logs of the server. That should give you a clue as to what is going on

**Comment by WesleyVerbrugge** [comment]
> Syntax wise I can't see any mistakes. However, a 500 indicates a server problem of some sorts. Are you running a VM? And if you are, does your VM know that it should redirect the api call back to itself? I.e. have you updated your VM hosts file? Postman would not have this issue since it runs from the host system and not the VM
> 
> If not, I'd add some logging in the API handler and/or check the error and access logs of the server. That should give you a clue as to what is going on

Thanks for the response Elimentz. Yea i am running my project on wampserver so thats most likely the issue. In that case i haven't updated anything in my hosts file. The end destination of this project will be on a online laradock image when its getting out of production so in that scenario it would most likely work.

Ill manage from here on, thanks again for the response 👍

**Comment by hoangthanhht** [comment]
when passing data to php to decode, you have to pass it as an object like this
async changeEnvSystem(context, {data = ''}) {
        console.log(data);
        let dataSend = {
                data:data
        }
        try {

            var result = await axiosInstance.post('/changeEnvironment', dataSend);
            console.log('result',result);
            return result
        } catch (error) {
            console.log("error", error);
        }
    },
