### ISSUE TITLE
Response is wrongfully being output to browser when using axios

### ISSUE THREAD

**Issue by graeme1995** [ixudra/curl#104]
I am doing an axios post request to a function in my controller. Inside this function I use a CURL POST to retrieve data from an API, but nowhere do I specify that I want to output the response back I simply just want to store it in the `$data` variable in my controller. The only data which should be included in the response is: ['success', 'Your application has been submitted.'], however the CURL response seems to prepend itself to the 'data' array in the response. Here is a snippet from my controller

```
$data = Raker::post($data, $url);
return response()->json(['success', 'Your application has been submitted.']);
```

My Raker class post function:

```
    public static function post($data, $url)
    {

        //Post data
        $response = Curl::to($url)
        ->withData( json_encode($data) )
        ->withContentType('text/json')
        ->withHeader('aeskey: ' . config('example.password'))
        ->withHeader('Authorization: ' . config('example.authorization'))
        ->withHeader('cache-control: no-cache')
        ->withHeader('salt: ' . config('example.salt'))
        ->returnResponseObject()
        ->post();


        //Return decrypted data
        return $response->content;

    }
```

For some reason, the CURL response (which contains sensitive data) is still being output into the browser when checking the Network tab in Chrome as well as when logging the response to the console using JS. 

How can i prevent CURL from giving a response to the browser and have it ONLY store in the $data variable. 

Thanks

**Comment by elimentz** [comment]
I see no reason why the package should add the response back to you in the browser. The only explanation I can see is that the request data is included in the `content` that you get back from the API, I've never seen the behavior that you describe. Did you do a `dd()` of the response? And of the response content? Can you show the results here? Or maybe a screenshot?

**Comment by graeme1995** [comment]
It turned out to be an issue with the third party provider, it is resolved now. Thanks for your help and this great package.
