### ISSUE TITLE
Cannot make request to localhost:8000

### ISSUE THREAD

**Issue by Jago-ral** [ixudra/curl#106]
*   Trying ::1...
* TCP_NODELAY set
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8000 (#0)
> POST /api/ecole HTTP/1.1
Host: localhost:8000
Accept: */*
Content-Length: 0
Content-Type: application/x-www-form-urlencoded

* Operation timed out after 30000 milliseconds with 0 bytes received
* Closing connection 0

**Comment by elimentz** [comment]
Hi, this usually occurs when you haven't set up your VM correctly. I assume you're using homestead (or something similar) and you're trying to send a request from your app to another URL of the same app? Well, your host computer knows what to do when you say `localhost:8000` but your VM doesn't. Not sure how to fix it, depends on your setup but it's not a problem with the package.

**Comment by elimentz** [comment]
Closed due to inactivity
