### ISSUE TITLE
array_collapse error

### ISSUE THREAD

**Issue by nam-co** [ixudra/curl#107]
Hi, thanks for the great package, in L6 Im getting "Call to undefined function Ixudra\Curl\array_collapse()" when using ->withResponseHeaders()->returnResponseObject()

File: vendor/ixudra/curl/src/Builder.php line 538

I was wondering if this is a L6 error?

Appreciate any help thanks

**Comment by elimentz** [comment]
Quite possibly.. I'll look at it this evening and fix it

**Comment by elimentz** [comment]
Fixed in version 6.17.0!
