### ISSUE TITLE
How to add a file array?

### ISSUE THREAD

**Issue by Porkts** [ixudra/curl#110]
If I put the same name with '[]' it overwrites

**Comment by elimentz** [comment]
Can you give me a clear example? Not sure I follow what you're asking here. Please provide a complete code sample with a good explanation of what the expected behavior is.

**Comment by Porkts** [comment]
I need to send an array of files, in a normal request I would put the same name in the input, like this:
`
<input type="file" name="photo[]">
<input type="file" name="photo[]">
`
How could I do the same with this package?
I would like something like this:

`$requisicao = Curl::to('http://saqsetl/caso/sendExtrato')
        ->withContentType('multipart/form-data')
        ->withData([ 'casoId' => 1])
        ->withFile("file", $photo1->getRealPath(), $photo1->getClientOriginalExtension())
        ->withFile("file", $photo2->getRealPath(), $photo2->getClientOriginalExtension())
        ->containsFile()
`

**Comment by elimentz** [comment]
You can just add multiple files to the request by using different keys:

```php
$requisicao = Curl::to('http://saqsetl/caso/sendExtrato')
    ->withContentType('multipart/form-data')
    ->withData([ 'casoId' => 1])
    ->withFile("file_1", $photo1->getRealPath(), $photo1->getClientOriginalExtension())
    ->withFile("file_2", $photo2->getRealPath(), $photo2->getClientOriginalExtension()) 
    ->containsFile() 
    ->post()
```

Note that both `withFile()` methods have different first parameters. These are the names that the files will have the submission. Keep in mind that you can't use any of the names in the `withData()` array. Well, you can, but they will override each other and you'll lose data.
