### ISSUE TITLE
Who send a token to header using jwt?

### ISSUE THREAD

**Issue by mzcoder-hub** [ixudra/curl#111]
This librart can send jwt token? Like
`Authorization bearer <token>`

How can i implementation that method ? That title should be how not who sorry

**Comment by elimentz** [comment]
Authorization is just a header, so you can just add it using the `withHeader()` method:



```php

    use Ixudra\Curl\Facades\Curl;

    $response = Curl::to('http://foo.com/bar')
        ->withHeader('Authorization: Bearer '. $token)
        ->get();

```
