### ISSUE TITLE
curl to https url , return false

### ISSUE THREAD

**Issue by ataraxia82** [ixudra/curl#117]
$response = Curl::to($url)->withOption('SSL_VERIFYHOST', false)->get();

$url is https://.................

can you tell me how to use CURL for https?

---------------------------
    "name": "ixudra/curl",
    "description": "Custom PHP Curl library for the Laravel 5 framework - developed by Ixudra",
    "version": "6.17.0",
    "keywords": ["Ixudra", "Laravel", "Curl"],
    "homepage": "http://ixudra.be",
    "license": "MIT",

**Comment by elimentz** [comment]
You can use this package with `https://` out of the box, no extra actions needed. If somethings goes wrong, it has nothing to do with `http` or `https`. I'd advise you to use the `enableDebug()` method to find out what is wrong. Please see the documentation for the details
