### ISSUE TITLE
Concurrent request for same link not working

### ISSUE THREAD

**Issue by sarfrajAbara** [ixudra/curl#124]
This is block of code I am using for send curl call, but this is not working when multiple user hit same curl URL then it is not responding. Some user get response some not dont know how to handle this.

**Note:** Parameter sent using withOption() are added for resolve this issue, but not working with this also

public static function get_curl_api_info_details($method = '', $url = '', $input_param = '', $file_data = '', $returnArray = true) { 
        $info = Curl::to(BASE_API_URL . $url); 
        $headers = array('authorization:Bearer' . ' ' . Session::get('theme_access_token')); 
        $info->withHeaders($headers); 
        $info->withOption('RETURNTRANSFER', true); 
        $info->withOption('SSL_VERIFYPEER', false); 
        $info->withOption('TIMEOUT_MS', 15000); 
        $info->withOption('LOW_SPEED_TIME', 60); 
        $info->withOption('LOW_SPEED_LIMIT', 30); 
        $info->withOption('FOLLOWLOCATION', false); 

        //if input parameters 

        if ($input_param != '') { 
            $info->withData($input_param); 
        } 
        //if file contains 
        if (isset($input_param['file_name']) && $file_data != '') { 
            $nameFile = $input_param['file_name']; 
            $info->withFile($nameFile, $file_data, $_FILES[$nameFile]['type'], $_FILES[$nameFile]['name']); 
        } else if ($file_data != '') { 
            $info->withFile('file', $file_data, $_FILES['file']['type'], $_FILES['file']['name']); 
        } 
       //check request method 
        if ($method == 'get') { 
           $get_curl_info = $info->get(); 
        } else { 
            $get_curl_info = $info->post(); 
        } 
   return $get_curl_info; 
          }

**Comment by elimentz** [comment]
Hi @sarfrajAbara This has, in all likelyhood, nothing to do with this package, Curl or sending requests in general. PHP is stateless, in which every incoming request is handled independently of all others by a separate process in the server. Basically that means that two requests have no way of interfering with each other. The only limitations here are shared resources, like your database for example, or the amount of processors on your machine (though I seriously doubt this is the cause, modern computers are more than capable of handling several requests per second).

It seems more likely that some other resource (file, database, session, cookie,...) is either locked or missing when the second request hits the server, which prevents it from working as intended. I recommend you add some logging to the code above (even better to the server which receives the request, if you control it) and see what the data looks like that comes in. My guess is you'll find what you'll looking for pretty quickly.

Feel free to open this issue again if the problem persists
