### ISSUE TITLE
Bad request

### ISSUE THREAD

**Issue by varun-gh** [ixudra/curl#127]
I am getting "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>400 Bad Request</title>\n</head><body>\n<h1>Bad Request</h1>\n<p>Your browser sent a request that this server could not understand.<br />\n</p>\n<p>Additionally, a 400 Bad Request\nerror was encountered while trying to use an ErrorDocument to handle the request.</p>\n</body></html>\n"
trying to get method

**Comment by varun-gh** [comment]
In laravel 6.2

**Comment by elimentz** [comment]
Please review the [Contribution guidelines](https://github.com/ixudra/curl/blob/master/CONTRIBUTING.md). You are not providing me with the basic information I need to help you
