### ISSUE TITLE
How to use Curl if url have redirect ?

### ISSUE THREAD

**Issue by valeriy-efimov** [ixudra/curl#15]
```
$inv = Curl::to('https://steamcommunity.com/profiles/76561198015712695/inventory/json/730/2/')
->get();
```

this code dont wort because redirect help pls

**Comment by swansun95** [comment]
Curl::to($url)->withOption("FOLLOWLOCATION", true);

hope it helps

**Comment by valeriy-efimov** [comment]
error( 
curl_setopt_array(): CURLOPT_FOLLOWLOCATION cannot be activated when an open_basedir is set

**Comment by swansun95** [comment]
try google it. it's not related with this curl package

http://stackoverflow.com/questions/6918623/curlopt-followlocation-cannot-be-activated

**Comment by elimentz** [comment]
I'm so happy I'm not the one who has to say it (again)... Thanks @swansun95 for your contribution!

**Comment by swansun95** [comment]
my pleasure :)
