### ISSUE TITLE
suggest to return Http status code

### ISSUE THREAD

**Issue by swansun95** [ixudra/curl#16]
it will be useful that there is a function to return HTTP status for a request.

**Comment by elimentz** [comment]
I assume you want the HTTP status combined with the HTML/JSON response and not instead of? Could you give me a use case of how you would like to use it? That would help me in making it functionally correct as well as intuitive to use.

**Comment by swansun95** [comment]
since the return value of the get() function is HTML/JSON content, i'm not sure if it's easy to add a HTTP status in it?

i would like to have such codes
$response = Curl::to($url)->get();
if(statusCode==200){
   // success, then get the content
}else{
  // do something else
}

**Comment by elimentz** [comment]
Well, there are two options, really:

The first is the easiest
```php
$responseStatus = Curl::to($url)->getStatus();
```
But if you also need the data, you'd have to do two requests, which would double the delay on your page. This might be ok in some situations, but most often this is not a good thing.

The second option is to encapsulate the response into a separate object:
```php
$response = Curl::to($url)->get();
$data = $responseObject->data;
$status = $responseObject->status;
```

More flexible, but it would reduce the simplicity of the package

**Comment by swansun95** [comment]
the second option is better, i think.

i guess the $responseObject is the $response?

but if the the return value of get() is an Object, what about the old scripts that using $response as HTML? would it be affected? then it would be a compatible problem？

**Comment by lthh89vt** [comment]
It's currently return as an json object.

So you can make it return as CurlResponse which has all the data of the json object + 1 extra method getStatus() or status().

By this way, it will keep the simplicity of this package and won't affect any existing script.

**Comment by elimentz** [comment]
Fixed in version 6.3.0:

```php
        $response = \Curl::to('http://someurl.com')
            ->withData( $data )
            ->returnResponseObject()
            ->get();

    $status = $response->status;
    $content = $response->content
```

**Comment by yansen-tan** [comment]
Hi, thank you for the fix. But the content returns null if the status code returns 422. How do I get the response data if I got the validation error from the API?

**Comment by elimentz** [comment]
@yansen-tan Can you give an example of what you get back and what kind of data you would like to see?

**Comment by yansen-tan** [comment]
Hi, thank you for replying. I managed to get the response using
withOption('FAILONERROR', false).

Thank you again. Problem solved
