### ISSUE TITLE
Curl Patch method

### ISSUE THREAD

**Issue by kikz4life** [ixudra/curl#19]
How about the curl patch? How would you do it using this? I have this web api that has PATCH. Tried using post and put to suffice the api but it failed. Please help

**Comment by elimentz** [comment]
Patch is basically the same as put, maybe you can try that? if not, I'll add it for you

**Comment by kikz4life** [comment]
When I used the put() method it gave me 404 page. So for now I'm using the php curl function. :(. Yes please it would be great if you add the PATCH method.

**Comment by elimentz** [comment]
This was added in the latest release (#6.4.0)
