### ISSUE TITLE
How to display http response code

### ISSUE THREAD

**Issue by kikz4life** [ixudra/curl#20]
I've tried adding curl options like 
->withOption('FAILONERROR', true)
->withOption('VERBOSE', true)

so I might get the error response code. But it always return null :(.

**Comment by kikz4life** [comment]
You can try with this api call. GET https://api.sendgrid.com/v3/contactdb/lists HTTP/1.1
The above api should be attach a authorization header, it should return a 403 FORBIDDEN http error code. I was thinking of catching those different http error response code in my end to alert the admin/user, etc..

**Comment by alonexy** [comment]
withdata有问题   get（） 可以扩展一下  a/b/c/d        return  false

**Comment by elimentz** [comment]
This is actually supported by the package:

```
$response = \Curl::to('https://api.sendgrid.com/v3/contactdb/lists')
            ->returnResponseObject()
            ->get();
```
This will give you the following response:
```
{
  +"content": false
  +"status": 401
}
```
