### ISSUE TITLE
Lumen 5.3 integration

### ISSUE THREAD

**Issue by zera272** [ixudra/curl#24]
i use it on lumen 5.3 and class Curl always not found, please the solution, thank you.

**Comment by elimentz** [comment]
In your `bootstrap/app.php`, make sure you've un-commented:

```
$app->withFacades();
```

Then, register you class alias with:
```
class_alias('Ixudra\Curl\Facades\Curl, 'Curl');
```

To register your ServiceProvider, check your `bootstrap/app.php`:

```
/*
|--------------------------------------------------------------------------
| Register Service Providers
|--------------------------------------------------------------------------
|
| Here we will register all of the application's service providers which
| are used to bind services into the container. Service providers are
| totally optional, so you are not required to uncomment this line.
|
*/

// $app->register('App\Providers\AppServiceProvider');

// Add your service provider here
$app->register('Ixudra\Curl\Providers\CurlServiceProvider');
```

For future reference though: I got this answer in less than 2 minutes on Google.. Please try (and try extensively) to find the answer yourself before asking another question like this

**Comment by zera272** [comment]
Thank you, it works well :)
