### ISSUE TITLE
Facing error - 400 bad request

### ISSUE THREAD

**Issue by hassansaqib** [ixudra/curl#28]
Hi, 

I have a code to which I have converted according to your way that looks more elegant and easier to understand but that is giving error.

The original code is 
$data = [ 'recipient'=>['id'=>$sender], 'message'=>['text'=>$message_to_reply]];

//Encode the array into JSON.
$jsonDataEncoded = $jsonData;
$jsonDataEncoded = json_encode ($data);
 
//Tell cURL that we want to send a POST request.
curl_setopt($ch, CURLOPT_POST, 1);
 
//Attach our encoded JSON string to the POST fields.
curl_setopt($ch, CURLOPT_POSTFIELDS, $jsonDataEncoded);
 
//Set the content type to application/json
curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type: application/json'));
//curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type: application/x-www-form-urlencoded'));

$fp = fopen('errorlogfb.txt', 'w');

curl_setopt($ch, CURLOPT_VERBOSE, 1);
curl_setopt($ch, CURLOPT_STDERR, $fp);
 
//Execute the request
if(!empty($input['entry'][0]['messaging'][0]['message'])){
    $result = curl_exec($ch);
}

and the one using your package is:

$response = Curl::to($url)
        ->withData($jsonData)
        ->withContentType('application/x-www-form-urlencoded')
        ->asJson()
        ->enableDebug('curlLogFile.txt')
        ->post();

The error that I am getting is:

* Hostname graph.facebook.com was found in DNS cache
*   Trying 31.13.93.3...
* Connected to graph.facebook.com (31.13.93.3) port 80 (#0)
> POST /v2.6/me/messages?access_token=iZALJPHCXDqZC9ZCTZAiT6Td4tBiZALJPHCXDqZC9ZCTZAiT6Td4tBiZALJPHCXDqZC9ZCTZAiT6Td4tBiZALJPHCXDqZC9ZCTZAiT6Td4tBiZALJPHCXDqZC9ZCTZAiT6Td4tBiZALJPHCXDqZC9ZCTZAiT6Td4tBiZALJPHCXDqZC9ZCTZAiT6Td4tBHTTP/1.1
Host: graph.facebook.com
Accept: */*
Content-Type: application/x-www-form-urlencoded
Connection: Keep-Alive
Content-Type: application/json
Content-Length: 143

* upload completely sent off: 143 out of 143 bytes
* The requested URL returned error: 400 Bad Request
* Closing connection 0

Kindly can you guide me what I am doing wrong?

**Comment by elimentz** [comment]
From a syntax point of view, your code is perfect. You use the library correctly so the request should yield a perfect response. I expect there is still a difference between your original method and the package method. At first glance, the only one I can see is the addition of the `application/x-www-form-urlencoded` content type, which is commented out in your initial request but added in the package version. Maybe try commenting that out in the package version too and see what that gives you?

**Comment by elimentz** [comment]
@hassansaqib Could you tell me what the status is of this issue? Is it resolved? Is it still open? If not, I will close it due to inactivity

**Comment by elimentz** [comment]
Closed due to inactivity
