### ISSUE TITLE
Basic/NTLM authentication and ignoring ssl certificate errors

### ISSUE THREAD

**Issue by f0nt4** [ixudra/curl#30]
Hi there,

Could you tell me how I can simply provide a name and password for basic/NTLM authentication in the request?
And how about ignoring ssl certificate errors, is this possible?

Thanks!

**Comment by f0nt4** [comment]
Found a way to disable the ssl certificate errors by adding 2 options:
```php
->withOption('SSL_VERIFYHOST', '0')
->withOption('SSL_VERIFYPEER', '0')
```

**Comment by elimentz** [comment]
I found the following on [StackOverflow](http://stackoverflow.com/questions/2140419/how-do-i-make-a-request-using-http-basic-authentication-with-php-curl):
```
curl_setopt($process, CURLOPT_USERPWD, $username . ":" . $password);  
```

In the package, this would look like this
```
->withOption('USERPWD', $username . ":" . $password)
```

Could you check and let me know if this works for you?

**Comment by f0nt4** [comment]
I tried numerous options, but they all just wouldn't work. I ended up using guzzlehttp which does work.

**Comment by 06chaynes** [comment]
@elimentz I know this is closed but I feel I should add that your solution worked for me without issue.
