### ISSUE TITLE
It's a pity that I can't work successfully with your plugin

### ISSUE THREAD

**Issue by vampirebitter** [ixudra/curl#32]
# KERNEL

Linux XPS 4.8.0-30-generic #32-Ubuntu SMP Fri Dec 2 03:43:27 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

# LARAVEL

I'am using Laravel 5.3，and I just follow your `README` to complete the function.However,it went wrong as I tried to display it on my browser。

# ERROR MESSAGE

Class 'App\Http\Controllers\Curl' not found

## HELP

I'am sure i have done what i should do .I have used composer to install your plugin and have added the alias and provider in my `app.php` file.However,it has the error message above.Can you give me a solusion?

**Comment by vampirebitter** [comment]
Here I have solved my problem , I just add `use Ixudra\Curl\Facades\Curl` in my Controller,and it worked.Thx a lot , it's really a good plugin

**Comment by elimentz** [comment]
Thanks, hope you enjoy it!
