### ISSUE TITLE
withData on GET request uses &amp;

### ISSUE THREAD

**Issue by MrToLLi** [ixudra/curl#34]
Hi there,

In Builder.php the appendDataToURL method uses http_build_query but doesn't specify an arg_seperator command as it does in the forgeOptions method. This results in GET params being built as GET /some/endpoint/?arg1=someValue&amp;arg2=anotherValue which causes problems for some web services as they expect just a plain '&'.

Is this by design? If not could the code be patched to specify the '&' as it does in the forgeOptions method?

Thanks

**Comment by elimentz** [comment]
Fixed in release 6.6.1, because you asked me nicely :-)

**Comment by MrToLLi** [comment]
Awesome, thanks!
