### ISSUE TITLE
Can not working with https

### ISSUE THREAD

**Issue by phambinh217** [ixudra/curl#39]
I am using method get to https://api.github.com/repos/phambinh217/cms/commits?since=2017-02-10T00:00:00Z
but its return false. please tell me why???

**Comment by elimentz** [comment]
Can you give me the full response that you have created?

**Comment by quinxy** [comment]
I'm having the same problem, presumably, I make what seems like a valid request and all I get in response is false.

Here is my code:

`								$response = Curl::to('https://pushcrew.com/api/v1/send/all')
								    ->withHeaders( array(
											'Authorization' => 'key=' . $pushCrewApiToken
								    	) )
								    ->withData( array(
											'title' => $pushTitle,
											'message' => $pushMessage,
											'url' => "https://pushcrew.com/api/v1/send/all"
								    	) )
								    ->post();`

I also tried "withHeader" singular, but with that I get array to string conversion error, so I presume the above is correct.

**Comment by falconz** [comment]
the same error

**Comment by elimentz** [comment]
Well, same question then.. Can you provide with the full syntax of the request you are trying to send?

**Comment by lbm-trentm** [comment]
@falconz & @phambinh217 - what operating system are you testing this on?

**Comment by sdfsky** [comment]
same error
my code is
`Curl::to($url)->withCurlOption('CURLOPT_SSL_VERIFYHOST','false')->withData($postData)->post()`

it shows error : Couldn't find constant CURLOPT_81

anyone can help me

**Comment by elimentz** [comment]
@sdfsky I think your problem is different from the others. Try the following:

```
Curl::to($url)
    ->withCurlOption('SSL_VERIFYHOST', false)
    ->withData($postData)
    ->post();
```

See the documentation: 
> You can add various cURL options to the request using of several utility methods such as withHeader() for adding a header to the request, or use the general withOption() method if no utility method applies. *The package will automatically prepend the options with the CURLOPT_ prefix.* It is worth noting that the package does not perform any validation on the cURL options. Additional information about available cURL options can be found here.

**Comment by sdfsky** [comment]
@elimentz   I update the version.now it works : )  . thank you :)

**Comment by elimentz** [comment]
Closed due to inactivity
