### ISSUE TITLE
Laravel 5.1 - Class 'Ixudra\Curl\CurlServiceProvider' not found

### ISSUE THREAD

**Issue by naurojunior** [ixudra/curl#4]
I don't know if it's only me, but I have Laravel 5.1

Added "ixudra/curl": "^5.1" on composer.js

When I add "Ixudra\Curl\CurlServiceProvider::class" on config/app.php and execute "composer install" the installation stops with the error "Class 'Ixudra\Curl\CurlServiceProvider' not found"

**Comment by elimentz** [comment]
when you make any changes to composer.json, you need to run composer update instead of install. The error occurs because the package has not been pulled in yet by composer.
