### ISSUE TITLE
Proxy Support.

### ISSUE THREAD

**Issue by matalla** [ixudra/curl#41]
Hi 
I would first thank you for the great work. I know I should not put this as an issue, but I did not know where to write it.

I want to ask if you have any plans to support making requests through a proxy ?

Thanks.

**Comment by elimentz** [comment]
Haven't made any plans for it, but I'd be happy to make it work if there is a need for it. Looking in to it briefly though, the package already has everything it needs to make it work. Based on [this article](https://beamtic.com/using-proxies-with-curl), it should work like this:

```php
/**
 * Native
 */

$ch = curl_init($url);
$url = "http://beamtic.com/Examples/http-post.php";
curl_setopt($ch, CURLOPT_PROXY, '128.0.0.3');
curl_setopt($ch, CURLOPT_PROXYPORT, '8080');

curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);

// The username and password
curl_setopt($ch, CURLOPT_PROXYUSERPWD, 'USERNAME:PASSWORD');

// Perform the request, and save content to $result
$result = curl_exec($ch);
echo $result;


/**
 * Package
 */

$response = Curl::to('http://beamtic.com/Examples/http-post.php')
    ->withOption('PROXY', '128.0.0.3')
    ->withOption('PROXYPORT', '8080')
    ->withOption('HTTPAUTH', CURLAUTH_BASIC)
    ->withOption('PROXYUSERPWD', 'USERNAME:PASSWORD')
    ->post();

```

Granted, it could use some cleanup, but it should to the trick. Haven't tested it though, will put some more thought into it in the near future. Also, feel free to submit a pull request to speed things up ;-)

**Comment by matalla** [comment]
Hi @elimentz 

Thank you very much, that's worked just great :)
