### ISSUE TITLE
Ways to make an authentication?

### ISSUE THREAD

**Issue by Fneves7** [ixudra/curl#47]
Hello everyone, I'm trying to "get" the data from the (Rest)api that I am using for my project, but I put the credentials to make the authentication and he gives me 'null' value, needless to say, it isn't make the authentication. I put the same values on postman and it can get the data.
What am I doing wrong? here is a sample of my code.
Thanks in advance

```
$curl = Curl::to($url)
            ->withData([
            'Content-Type' => 'application/json',   
            'EMAIL' => 'email',
            'KEY' => 'key'])
->asJson()
->get();
```

**Comment by elimentz** [comment]
Hard to say without seeing your code, but a couple improvements I would suggest right away: you should remove the content type, the `->asJson()` method does that for you.

You would add the `->returnResponseObject()` method, which will give you some more details on what went wrong

**Comment by Fneves7** [comment]
Thanks, it gives me unauthorized error code, but I put the correct information, I am starting to think that is problem with the API :\
Here is the ResponseObject:
```
{#266 ▼
  +"content": ""
  +"status": 401
}
```
By checking with more attention to the cURL provided and the code I realized that the credentials for authentication are custom headerlines (ノº益º)ノ彡┻━┻

My code right now,  and it still giving me the error 401(unauthorized),

```
public function index()
    {
	$url= 'https://exampleApi.com';
	$curl = Curl::to($url)
	            ->withHeaders([
	            'Content-Type' => 'application/json',   
	            'X-EMAIL' => 'user@example.com',
	            'X-KEY' => 'the-key-of-the-api'])
	            ->returnResponseObject()
                    ->get();
         dd($curl);
        return view('views.index');
    }
```
The curl that they provided to me to consume the api is like this:

`curl -H 'Content-Type: application/json' -H 'X-EMAIL: user@example.com' -H 'X-KEY: examplekey' "https://exampleApi.com"`

Im just getting bald with the api because this package works fine with other things  ┬─┬ノ( º _ ºノ)

**Comment by Fneves7** [comment]
I manage to solve! Instead of put the headers in array I have to put individually to fetch one by one

Like this:
`        public function index()
    {
	$url= 'https://exampleApi.com';
	$curl = Curl::to($url)
	            ->withHeader('Content-Type' => 'application/json')
	            ->withHeader('X-EMAIL' => 'user@example.com')
	            ->withHeader('X-KEY' => 'the-key-of-the-api')
	            ->returnResponseObject()
                    ->get();
         dd($curl);
        return view('views.index');
    }`

Thanks one more time! We can close the issue.
