### ISSUE TITLE
ixudra/curl withHeaders method not sending custom header

### ISSUE THREAD

**Issue by jiturawat94** [ixudra/curl#48]
i tried sending a custom header "token" to an api  but its not sending

**Comment by elimentz** [comment]
See documentation:

 > Note before posting an issue: When posting an issue for the package, always be sure to provide as much information 
 > regarding the request as possible. This includes the example cURL request you are trying to transfer into the package
 > syntax, your actual package syntax (the full request) and (if possible) an example URL I can use to test the request
 > myself if need be.

**Comment by jiturawat94** [comment]
this is my function

public static function request ($url = '', $data = array()) {
        $header=[
            'TokenType'=>'web'
        ];
        if(Session::has('user_session.0')){
            $header['Token']=Session::get('user_session.0')->token;
        }
        if ((trim($url) != '') && isset($url)) {
            $to = config('app.API_URL').'/v1'.$url;
            $curlReqObj = Curl::to($to);
            if (isset($data) && !empty($data)) {
             $curlReqObj = $curlReqObj->withData($data);
            }
            $curlReqObj = $curlReqObj->withHeaders($header);
                $response = $curlReqObj->withTimeout(config('app.DEFAULT_CURL_TIMEOUT'))->post();
            //dd($response);
            $response = json_decode($response);
            return $response;
        } else {
            $errorArr = array ('ERROR' => 'Error while accessing api!');
            $response = json_encode($errorArr);
            return $response;
        }    
    }


and my api is
public function testApi () {
    $header=apache_request_headers();
    return $header;
}

**Comment by elimentz** [comment]
Your headers should not be key-value, but rather just an array. Try the following:

```
public static function request ($url = '', $data = array()) {
        $header[] = 'TokenType: web';
        if(Session::has('user_session.0')){
            $header[] = 'Token:'. Session::get('user_session.0')->token;
        }
        if ((trim($url) != '') && isset($url)) {
            $to = config('app.API_URL').'/v1'.$url;
            $curlReqObj = Curl::to($to);
            if (isset($data) && !empty($data)) {
             $curlReqObj = $curlReqObj->withData($data);
            }
            $curlReqObj = $curlReqObj->withHeaders($header);
                $response = $curlReqObj->withTimeout(config('app.DEFAULT_CURL_TIMEOUT'))->post();
            //dd($response);
            $response = json_decode($response);
            return $response;
        } else {
            $errorArr = array ('ERROR' => 'Error while accessing api!');
            $response = json_encode($errorArr);
            return $response;
        }    
    }
```

**Comment by jiturawat94** [comment]
thanks @elimentz
