### ISSUE TITLE
Errror "Array to string conversion" when using containsFile()

### ISSUE THREAD

**Issue by lchhieu** [ixudra/curl#49]

**Comment by elimentz** [comment]
See documentation:

> Note before posting an issue: When posting an issue for the package, always be sure to provide as much information regarding the request as possible. This includes the example cURL request you are trying to transfer into the package syntax, your actual package syntax (the full request) and (if possible) an example URL I can use to test the request myself if need be.

**Comment by jiturawat94** [comment]
im using this
$response = Curl::to($to)
        ->withData( $data)
        ->withContentType('multipart/form-data')
        ->containsFile()
        ->post();

and when im trying to return 
$request->get('paymentProof');

its returning a string 
'C:\wamp64\tmp\php510E.tmp'

**Comment by elimentz** [comment]
Closed due to inactivity
