### ISSUE TITLE
Which errors occur during use？How to handle them？

### ISSUE THREAD

**Issue by TechZi** [ixudra/curl#51]
Which errors occur during use？How to handle them？

**Comment by elimentz** [comment]
Pretty much any error in PHP can occur as far as I can tell, it mostly depends on what input you provide to the functions. Please read the documentation as well as the source code to make sure you use all features as intended.

As far as handling exceptions, just use a try-catch as you would any other time:

```php
try {
    $response = Curl::to('http://www.foo.com/bar')
        ->withData( array( 'foz' => 'baz' ) )
        ->asJson()
        ->get();
} catch( Exception $e ) {
    // Do something here
}
```

**Comment by TechZi** [comment]
@elimentz Thank you
