### ISSUE TITLE
I don't have any issue I have a suggestion

### ISSUE THREAD

**Issue by faisalwiz** [ixudra/curl#52]
Hi ixudra/curl is awesome library I have suggestion can you please add asArray() method like asJson().

**Comment by elimentz** [comment]
@faisalwiz What exactly would this do? I assume return the response as an associative array instead of a `stdClass`?

**Comment by faisalwiz** [comment]
Thanks for replying,
great idea so you can return it as an array when asArray method called and return it as stdClass Object when asArrayObj method called,
you can define both methods asArrayObj and asArray

**Comment by elimentz** [comment]
Added in v 6.12.0

```
        $response = \Curl::to('http://foo.com/bar')
            ->withData( array( 'Foo' => 'Bar' ) )
            ->returnResponseArray()
            ->get();
```

Thanks for suggesting and apologies for the delay
