### ISSUE TITLE
format of data following URL

### ISSUE THREAD

**Issue by arnoldjp57** [ixudra/curl#58]
Hi ... I am struggling to get the body of my get request formatted correctly .... if I send the string maually to the URL it works 100% .....

https://url?
followed by
 `api_key=xxxxxxxxxxxxxxxxxxxx&entitynr=1&ilikedict=%7B%22debtor_surname%22%3A%22%25test%25%22%7D&operator=&orderby=&orderdirection=&limit=`

Here is my array

`$arr = [
             'api_key' => 'xxxxxxxxxxxxxxxxxxxx',
             'entitynr' =>'1',
             'ilikedict' => ['debtor_surname' => '%test%'],
             'operator' => '',
              'orderby' => '',
              'orderdirection' => '',
              'limit' => '', 
            ];  `

Here is the command ...

` $response = Curl::to($url)
          ->withData( $arr )
          ->asJson()
          ->get();
`

**Comment by arnoldjp57** [comment]
Sorry, here is the response I get

`2017-07-10 13:20:38: stdClass::__set_state(array(
   'content' =>
  stdClass::__set_state(array(
     'msg' => 'searchDebtorApi() got an unexpected keyword argument \'ilikedict[debtor_surname]\'',
     'result' => false,
     'data' => NULL,
  )),
   'status' => 200,
))
`

**Comment by elimentz** [comment]
I think you need to get rid of the `asJson()` function. When used, it will convert your data in a json string, which the server cannot interpret. Try removing it or replacing it with `asJsonResponse()` if the server returns json to you
