### ISSUE TITLE
Curl request Error: Undefined index: http_code

### ISSUE THREAD

**Issue by MrJmpl3** [ixudra/curl#63]
(1/1) ErrorExceptionUndefined index: http_code
--
in Builder.php (line 487)

at HandleExceptions->handleError(8, 'Undefined index: http_code', '/var/www/vendor/ixudra/curl/src/Builder.php', 487, array('content' =>array('status' => 'success', 'shortenedUrl' => 'http://u2s.io/XXuu'), 'responseData' => array(), 'object' => object(stdClass)))in Builder.php (line 487)

at Builder->returnResponse(array('status' => 'success', 'shortenedUrl' => 'http://u2s.io/XXuu'), array())in Builder.php (line 475)

In local , works , but in deploy dont work .. any ideas?

**Comment by elimentz** [comment]
Please provide the full request you are trying to send.

**Comment by elimentz** [comment]
Fixed in v 6.12.1
