### ISSUE TITLE
Json post does not work

### ISSUE THREAD

**Issue by 3ngin** [ixudra/curl#65]
Hi guys,
my project code he is working

$vars =array(
    'seedShowing' => true,
    'rootShowing' => true,
    'parentShowing' => true,
    'productShowing' => true,
    'metaShowing' => true,
    'priceShowing' => true,
    'uriShowing' => true,
    'tagShowing' => true
);

$requestbody = json_encode($vars);

$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, "http://127.0.0.1:8000/new/products/list");
curl_setopt($ch, CURLOPT_POST, TRUE);
curl_setopt($ch, CURLOPT_POSTFIELDS, $requestbody);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);

$headers = array(
    'Accept:application/json',
    'Content-Type:application/json',
    'Authorization:Bearer '.$token
);

curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$responsebody = curl_exec($ch);

curl_close($ch);

-----------
You are code not working on my project, Where do i make mistakes

$vars =array(
    'seedShowing' => true,
    'rootShowing' => true,
    'parentShowing' => true,
    'productShowing' => true,
    'metaShowing' => true,
    'priceShowing' => true,
    'uriShowing' => true,
    'tagShowing' => true
);

$headers = array(
    'Accept:application/json',
    'Authorization:Bearer '.$token
);
$product = Curl::to('http://127.0.0.1:8000/new/products/list')
        ->withData($vars)
        ->withHeaders($headers)
        ->withContentType('application/json')
        ->asJson()
        ->post();

**Comment by elimentz** [comment]
Your code looks correct as far as I can see. What is the response you receive from the server?

**Comment by elimentz** [comment]
Closed due to inactivity
