### ISSUE TITLE
Conditional options

### ISSUE THREAD

**Issue by bhavikshah9** [ixudra/curl#72]
How to add conditional options?
Use case: When project is in local environment, add proxy headers, otherwise not.

__Snippet 1__ - not working
```
$response = Curl::to('https://jsonplaceholder.typicode.com/posts');
if (\App::environment('local')) {
  $response->withOption('PROXY', '192.168.10.5')
    ->withOption('PROXYPORT', '8080');
}
$response->get();
```
__Snippet 2__ - working
```
$response = Curl::to('https://jsonplaceholder.typicode.com/posts')
      ->withOption('PROXY', '192.168.10.5')
      ->withOption('PROXYPORT', '8080')
      ->get();
```

**Comment by elimentz** [comment]
The package is not a singleton, so you need to "capture" the builder instance after adding a new option. Like this:

```
$builder = Curl::to('https://jsonplaceholder.typicode.com/posts');
if (\App::environment('local')) {
  $builder = $builder->withOption('PROXY', '192.168.10.5')               // Diff here
    ->withOption('PROXYPORT', '8080');
}
$response = $builder->get();
```

**Comment by bhavikshah9** [comment]
Hi @elimentz,

Thanks for prompt reply. Rare. Earlier, I loved your package. Now, I loved your passion. Keep rocking.
I tried to capture the builder instance within `if` condition like you mentioned above but it was not working. But then, after your comment, I realized that I need to capture it outside `if` as well. You have done it right in your comment. I have just highlighted it here so it comes to notice.
```
$builder = Curl::to('https://jsonplaceholder.typicode.com/posts');
if (\App::environment('local')) {
  $builder = $builder->withOption('PROXY', '192.168.10.5')               // Diff here
    ->withOption('PROXYPORT', '8080');
}
$response = $builder->get();                                             // Same Diff here <------
```
