### ISSUE TITLE
how to use ldap and auth when i want to use get ? provide an example please

### ISSUE THREAD

**Issue by jihadismail8** [ixudra/curl#77]

**Comment by elimentz** [comment]
LDAP is a protocol, there is no way I can give you an example for the specific installation you are referring to

**Comment by jihadismail8** [comment]
i used to do like this , in pure PHP , could you please guide me how to do the same and auth by LDP then i make get and post request please :)  here is how i used to do it : 

    $ch = curl_init();
    curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
    curl_setopt($ch, CURLOPT_USERPWD, $LDPusername . ":" . $LDPpassword);


    curl_setopt($ch, CURLOPT_URL, $url);

    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

    curl_setopt($ch, CURLOPT_POST, 1);

    curl_setopt($ch, CURLOPT_POSTFIELDS, $post_data);

    $output = curl_exec($ch);
    curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 30); 

    curl_setopt($ch, CURLOPT_TIMEOUT, 60); 
    curl_close($ch);

**Comment by elimentz** [comment]
```php
    // Original
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
    curl_setopt($ch, CURLOPT_USERPWD, $LDPusername . ":" . $LDPpassword);
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, $post_data);
    $output = curl_exec($ch);
    curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 30); 
    curl_setopt($ch, CURLOPT_TIMEOUT, 60); 
    curl_close($ch);

    // ixudra/curl
    $response = Curl::to($url)
        ->withOption('HTTPAUTH', CURLAUTH_BASIC)
        ->withOption('USERPWD', $LDPusername . ":" . $LDPpassword)
        ->withOption('CONNECTTIMEOUT', 30)
        ->withTimeout(60)
        ->withData( $post_data )
        ->post();
```
