### ISSUE TITLE
Call to undefined method Ixudra\Curl\Builder::withResponseHeaders()

### ISSUE THREAD

**Issue by smartyaunt** [ixudra/curl#80]
$response = \Ixudra\Curl\Facades\Curl::to($url)
                  ->withResponseHeaders()
                  ->returnResponseObject()
                  ->get();

I get error
 -----Call to undefined method Ixudra\Curl\Builder::withResponseHeaders()

lumen  composer.json  "ixudra/curl": "^6.11"
please help me bro

**Comment by elimentz** [comment]
Please check which version you have installed. This feature was added in v6.16.0 (latest version). If yours doesn't match, run composer update.

**Comment by smartyaunt** [comment]
@elimentz NIce bro, it work, thanks
