### ISSUE TITLE
Double request on one function

### ISSUE THREAD

**Issue by shadowgroundz** [ixudra/curl#85]
Hi, I want to make 2 request to https://api.aftership.com/v4/trackings. Let say 1 process I want to use POST method to create tracking data and then I want to use GET method to get tracking data 

OR 

1st I want to get tracking data with number XXX and next with YYY

I can not use it 2 times if in 1 process. Only 1 of them can produce result. Usually in php native I open and Close curl to do that. What's a problem? Maybe you can use easy language because I'm still learning :D

**Comment by elimentz** [comment]
You can do as many requests in one function as you want. Every time you call the facade (or the CurlService) a new request is generated.

This will do the trick:

```php
    public function yourFunction()
    {
        $response1 = Curl::to('https://api.aftership.com/v4/trackings')
            ->get();

        $response2 = Curl::to('https://api.aftership.com/v4/trackings')
            ->withData( array( 'foz' => 'baz' ) )
            ->post();

        $response3 = Curl::to('https://api.aftership.com/v4/trackings')
            ->withData( array( 'foz' => 'baz' ) )
            ->asJson()
            ->get();
    }
```

If you don't use Laravel, it would look something like this:

```php
    public function yourFunction()
    {
        $curlService = new \Ixudra\Curl\CurlService();
        $response1 = $curlService->to('https://api.aftership.com/v4/trackings')
            ->get();

        $response2 = $curlService->to('https://api.aftership.com/v4/trackings')
            ->withData( array( 'foz' => 'baz' ) )
            ->post();

        $response3 = $curlService->to('https://api.aftership.com/v4/trackings')
            ->withData( array( 'foz' => 'baz' ) )
            ->asJson()
            ->get();
    }
```

Nice and easy

**Comment by shadowgroundz** [comment]
Yes, look too easy. But, different result. When I use : 

`
$response1 = Curl::to('https://api.aftership.com/v4/trackings')->get();
$response2 = Curl::to('https://api.aftership.com/v4/trackings')->withData( array( 'foz' => 'baz' ) )->post();
$result1 = json_decode($response1);
$result2 = json_decode($response2);
var_dump($result2);
`

The result is value on $result1, not $result2. Why?

**Comment by elimentz** [comment]
I would assume that you are not passing the right parameters to the API, difficult to say without seeing the actual code. You can easily check by doing 2 requests to 2 different URLs, e.g. google.com and facebook.com. You'll see the results are quite different

**Comment by shadowgroundz** [comment]
I think everyhing okay. Bcause when I call 
`
$response1 = Curl::to('https://api.aftership.com/v4/trackings')->get(); 
$result1 = json_decode($response1); 
dd($result1);
`

Result correct for `$result1`. Then I call again 

`
$response2 = Curl::to('https://api.aftership.com/v4/trackings')->get(); 
$result2 = json_decode($response2); 
dd($result2);
`
Result correct for `$result2`. But I call $result1 and $result2 in same function, result only show $result2 (not using `dd` definitely)

**Comment by shadowgroundz** [comment]
Here. You can see my screenshot
https://imgur.com/a/tQltg

**Comment by elimentz** [comment]
Like I said earlier: you are passing the wrong parameters. In both requests, you are submitting `$courir1` and `$trackingnumber1`, essentially you're doing the same request twice. Change those parameters and you'll be fine

**Comment by shadowgroundz** [comment]
Sorry, it's my fault. I deleted wrong screenshot. Look this

1. I try to create data : https://imgur.com/PEzkdsv
2. I try to get data https://imgur.com/1xbwR0z
3. When I run 2 code in same time https://imgur.com/ULcfrOw

Why show different result? I predicted result can same with when I use GET code because I call $resultlog variable

**Comment by elimentz** [comment]
Based on your code, I would guess the same: the result of `dd($resultlog)` should be the same as with only the GET request. That said, I have no idea how the aftership API works and I would assume there is still something wrong with the parameters you are submitting. I ran a couple of tests with other websites and they all seem to work perfectly fine. As far as I can see, the package is not to blame. 

Maybe you can contact them and ask for some information regarding their API?
