### ISSUE TITLE
Url with port return null

### ISSUE THREAD

**Issue by zarulizham** [ixudra/curl#86]
I tried to GET request from https://cryptottlivewebapi.b2bx.exchange:8443/api/v1/public/currency but return null. While I try surf using browser using same address, there's data returned. Is there any settings that I missed?

**Comment by elimentz** [comment]
Hard for me to tell if you don't give me any source code to look at...

**Comment by zarulizham** [comment]
`$response = Curl::to('https://cryptottlivewebapi.b2bx.exchange:8443/api/v1/public/currency')
            ->withContentType('application/json')
            ->allowRedirect()
            ->get();`

Noted that I already include:

`use Illuminate\Http\Request;
use Ixudra\Curl\Facades\Curl;`

**Comment by elimentz** [comment]
Your syntax is correct. I updated your request to see what is going on using the `->enableDebug()` method and got back in the log:

```
* Hostname in DNS cache was stale, zapped
*   Trying 98.158.104.72...
* Connected to cryptottlivewebapi.b2bx.exchange (98.158.104.72) port 8443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
* 	 subject: OU=Domain Control Validated; OU=PositiveSSL Wildcard; CN=*.b2bx.exchange
* 	 start date: Aug 21 00:00:00 2017 GMT
* 	 expire date: Aug 21 23:59:59 2018 GMT
* 	 subjectAltName: cryptottlivewebapi.b2bx.exchange matched
* 	 issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=COMODO RSA Domain Validation Secure Server CA
* 	 SSL certificate verify ok.
> GET /api/v1/public/currency HTTP/1.1
Host: cryptottlivewebapi.b2bx.exchange:8443
Accept: */*
Content-Type: application/json
Connection: Keep-Alive

< HTTP/1.1 415 Unsupported Media Type
< Content-Length: 0
< Server: Microsoft-HTTPAPI/2.0
< Date: Mon, 02 Apr 2018 18:57:54 GMT
< 
* Connection #0 to host cryptottlivewebapi.b2bx.exchange left intact
```

As you can see, the error message is `HTTP/1.1 415 Unsupported Media Type`, not sure why or what you need to do to solve it - probably have to add some headers if I had to guess. In any case, you have to take this up with the website owner, it has nothing to do with the package.
