### ISSUE TITLE
Ideal Way to Log response and request payload in debug file 

### ISSUE THREAD

**Issue by chintanbanugaria** [ixudra/curl#93]
Hey,
A quick question. What is the ideal way to store the request and response payload of each request in the debug file ?

Thanks,
Chintan

**Comment by elimentz** [comment]
I don't think you can. The debug file that is generated when you use the `debug()` method is generated by curl itself, the package has no control over it. And aside from that, there are no methods in the package that will allow you to log it. I'm afraid you'll have to do that yourself. You'll have to wrap the curl request into a service and add the info to a file manually. It can be done.
